apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nodeport-service
  namespace: {{ .Values.common.namespace }}
spec:
  type: NodePort
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007
