kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-secrets-reader
  namespace: {{ .Values.common.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.common.namespace }}
  name: {{ .Chart.Name }}-secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-secrets-reader-binding
  namespace: {{ .Values.common.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-secrets-reader
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-secrets-reader
  apiGroup: rbac.authorization.k8s.io